// source: sdk/stream/trades_v1/response.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var sdk_core_wrappers_pb = require('../../../sdk/core/wrappers_pb.js');
goog.object.extend(proto, sdk_core_wrappers_pb);
goog.exportSymbol('proto.kaikosdk.StreamTradesResponseV1', null, global);
goog.exportSymbol('proto.kaikosdk.StreamTradesResponseV1.TradeSide', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kaikosdk.StreamTradesResponseV1 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kaikosdk.StreamTradesResponseV1, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kaikosdk.StreamTradesResponseV1.displayName = 'proto.kaikosdk.StreamTradesResponseV1';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.toObject = function(opt_includeInstance) {
  return proto.kaikosdk.StreamTradesResponseV1.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kaikosdk.StreamTradesResponseV1} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kaikosdk.StreamTradesResponseV1.toObject = function(includeInstance, msg) {
  var f, obj = {
    additionalPropertiesMap: (f = msg.getAdditionalPropertiesMap()) ? f.toObject(includeInstance, undefined) : [],
    amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    pb_class: jspb.Message.getFieldWithDefault(msg, 3, ""),
    code: jspb.Message.getFieldWithDefault(msg, 4, ""),
    exchange: jspb.Message.getFieldWithDefault(msg, 5, ""),
    sequenceId: jspb.Message.getFieldWithDefault(msg, 6, ""),
    id: jspb.Message.getFieldWithDefault(msg, 7, ""),
    price: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    side: jspb.Message.getFieldWithDefault(msg, 9, 0),
    tsExchange: (f = msg.getTsExchange()) && sdk_core_wrappers_pb.TimestampValue.toObject(includeInstance, f),
    tsCollection: (f = msg.getTsCollection()) && sdk_core_wrappers_pb.TimestampValue.toObject(includeInstance, f),
    tsEvent: (f = msg.getTsEvent()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kaikosdk.StreamTradesResponseV1}
 */
proto.kaikosdk.StreamTradesResponseV1.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kaikosdk.StreamTradesResponseV1;
  return proto.kaikosdk.StreamTradesResponseV1.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kaikosdk.StreamTradesResponseV1} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kaikosdk.StreamTradesResponseV1}
 */
proto.kaikosdk.StreamTradesResponseV1.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getAdditionalPropertiesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setClass(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setExchange(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSequenceId(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPrice(value);
      break;
    case 9:
      var value = /** @type {!proto.kaikosdk.StreamTradesResponseV1.TradeSide} */ (reader.readEnum());
      msg.setSide(value);
      break;
    case 10:
      var value = new sdk_core_wrappers_pb.TimestampValue;
      reader.readMessage(value,sdk_core_wrappers_pb.TimestampValue.deserializeBinaryFromReader);
      msg.setTsExchange(value);
      break;
    case 11:
      var value = new sdk_core_wrappers_pb.TimestampValue;
      reader.readMessage(value,sdk_core_wrappers_pb.TimestampValue.deserializeBinaryFromReader);
      msg.setTsCollection(value);
      break;
    case 12:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTsEvent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kaikosdk.StreamTradesResponseV1.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kaikosdk.StreamTradesResponseV1} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kaikosdk.StreamTradesResponseV1.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAdditionalPropertiesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getClass();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getExchange();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getSequenceId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getSide();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getTsExchange();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      sdk_core_wrappers_pb.TimestampValue.serializeBinaryToWriter
    );
  }
  f = message.getTsCollection();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      sdk_core_wrappers_pb.TimestampValue.serializeBinaryToWriter
    );
  }
  f = message.getTsEvent();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.kaikosdk.StreamTradesResponseV1.TradeSide = {
  UNKNOWN: 0,
  BUY: 1,
  SELL: 2
};

/**
 * map<string, string> additional_properties = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.getAdditionalPropertiesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.clearAdditionalPropertiesMap = function() {
  this.getAdditionalPropertiesMap().clear();
  return this;};


/**
 * optional double amount = 2;
 * @return {number}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional string class = 3;
 * @return {string}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.getClass = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.setClass = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string code = 4;
 * @return {string}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string exchange = 5;
 * @return {string}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.getExchange = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.setExchange = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string sequence_id = 6;
 * @return {string}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.getSequenceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.setSequenceId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string id = 7;
 * @return {string}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional double price = 8;
 * @return {number}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.setPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional TradeSide side = 9;
 * @return {!proto.kaikosdk.StreamTradesResponseV1.TradeSide}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.getSide = function() {
  return /** @type {!proto.kaikosdk.StreamTradesResponseV1.TradeSide} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.kaikosdk.StreamTradesResponseV1.TradeSide} value
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.setSide = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * optional TimestampValue ts_exchange = 10;
 * @return {?proto.kaikosdk.TimestampValue}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.getTsExchange = function() {
  return /** @type{?proto.kaikosdk.TimestampValue} */ (
    jspb.Message.getWrapperField(this, sdk_core_wrappers_pb.TimestampValue, 10));
};


/**
 * @param {?proto.kaikosdk.TimestampValue|undefined} value
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
*/
proto.kaikosdk.StreamTradesResponseV1.prototype.setTsExchange = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.clearTsExchange = function() {
  return this.setTsExchange(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.hasTsExchange = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional TimestampValue ts_collection = 11;
 * @return {?proto.kaikosdk.TimestampValue}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.getTsCollection = function() {
  return /** @type{?proto.kaikosdk.TimestampValue} */ (
    jspb.Message.getWrapperField(this, sdk_core_wrappers_pb.TimestampValue, 11));
};


/**
 * @param {?proto.kaikosdk.TimestampValue|undefined} value
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
*/
proto.kaikosdk.StreamTradesResponseV1.prototype.setTsCollection = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.clearTsCollection = function() {
  return this.setTsCollection(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.hasTsCollection = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional google.protobuf.Timestamp ts_event = 12;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.getTsEvent = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 12));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
*/
proto.kaikosdk.StreamTradesResponseV1.prototype.setTsEvent = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kaikosdk.StreamTradesResponseV1} returns this
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.clearTsEvent = function() {
  return this.setTsEvent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kaikosdk.StreamTradesResponseV1.prototype.hasTsEvent = function() {
  return jspb.Message.getField(this, 12) != null;
};


goog.object.extend(exports, proto.kaikosdk);
