# docker-compose.core.yml

version: "3"
services:
  db:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    volumes:
      - ./tmp/${COMPOSE_PROJECT_NAME}/fs/mongo:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - core-network

  cache:
    image: redis:5.0-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/${COMPOSE_PROJECT_NAME}/fs/redis:/data
    networks:
      - core-network

  timeseries:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./tmp/${COMPOSE_PROJECT_NAME}/fs/influx:/data
    networks:
      - core-network
networks:
  core-network:
