// source: sdk/stream/aggregates_direct_exchange_rate_v1/response.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var sdk_core_source_data_pb = require('../../../sdk/core/source_data_pb.js');
goog.object.extend(proto, sdk_core_source_data_pb);
goog.exportSymbol('proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.repeatedFields_, null);
};
goog.inherits(proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.displayName = 'proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.toObject = function(opt_includeInstance) {
  return proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.toObject = function(includeInstance, msg) {
  var f, obj = {
    aggregate: jspb.Message.getFieldWithDefault(msg, 1, ""),
    code: jspb.Message.getFieldWithDefault(msg, 2, ""),
    price: jspb.Message.getFieldWithDefault(msg, 3, ""),
    sequenceId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    sourcesList: jspb.Message.toObjectList(msg.getSourcesList(),
    sdk_core_source_data_pb.SourceData.toObject, includeInstance),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    uid: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1}
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1;
  return proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1}
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAggregate(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrice(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSequenceId(value);
      break;
    case 5:
      var value = new sdk_core_source_data_pb.SourceData;
      reader.readMessage(value,sdk_core_source_data_pb.SourceData.deserializeBinaryFromReader);
      msg.addSources(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAggregate();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPrice();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSequenceId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getSourcesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      sdk_core_source_data_pb.SourceData.serializeBinaryToWriter
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUid();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string aggregate = 1;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.getAggregate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.setAggregate = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string code = 2;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string price = 3;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.getPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.setPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string sequence_id = 4;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.getSequenceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.setSequenceId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated SourceData sources = 5;
 * @return {!Array<!proto.kaikosdk.SourceData>}
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.getSourcesList = function() {
  return /** @type{!Array<!proto.kaikosdk.SourceData>} */ (
    jspb.Message.getRepeatedWrapperField(this, sdk_core_source_data_pb.SourceData, 5));
};


/**
 * @param {!Array<!proto.kaikosdk.SourceData>} value
 * @return {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1} returns this
*/
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.setSourcesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.kaikosdk.SourceData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.kaikosdk.SourceData}
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.addSources = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.kaikosdk.SourceData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.clearSourcesList = function() {
  return this.setSourcesList([]);
};


/**
 * optional google.protobuf.Timestamp timestamp = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1} returns this
*/
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string uid = 7;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesDirectExchangeRateResponseV1.prototype.setUid = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


goog.object.extend(exports, proto.kaikosdk);
