export enum TimeoutCodes {
  CRYPTOCOMPARE = 1,
  COINGECKO,
  COINMARKETCAP,
  GENESISVOLATILITY,
  POLYGON_IO,
  IEX,
  BEA,
  KAIKO,
  OPTIONS_PRICE,
  STATUS_CHECK_TIMEOUT,
  SIGNATURE_TIMEOUT,
}
