// source: sdk/stream/aggregates_ohlcv_v1/response.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.kaikosdk.StreamAggregatesOHLCVResponseV1', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kaikosdk.StreamAggregatesOHLCVResponseV1, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kaikosdk.StreamAggregatesOHLCVResponseV1.displayName = 'proto.kaikosdk.StreamAggregatesOHLCVResponseV1';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.toObject = function(opt_includeInstance) {
  return proto.kaikosdk.StreamAggregatesOHLCVResponseV1.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.toObject = function(includeInstance, msg) {
  var f, obj = {
    aggregate: jspb.Message.getFieldWithDefault(msg, 1, ""),
    pb_class: jspb.Message.getFieldWithDefault(msg, 2, ""),
    close: jspb.Message.getFieldWithDefault(msg, 3, ""),
    exchange: jspb.Message.getFieldWithDefault(msg, 4, ""),
    high: jspb.Message.getFieldWithDefault(msg, 5, ""),
    low: jspb.Message.getFieldWithDefault(msg, 6, ""),
    open: jspb.Message.getFieldWithDefault(msg, 7, ""),
    sequenceId: jspb.Message.getFieldWithDefault(msg, 8, ""),
    code: jspb.Message.getFieldWithDefault(msg, 9, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    uid: jspb.Message.getFieldWithDefault(msg, 11, ""),
    volume: jspb.Message.getFieldWithDefault(msg, 12, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kaikosdk.StreamAggregatesOHLCVResponseV1;
  return proto.kaikosdk.StreamAggregatesOHLCVResponseV1.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAggregate(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setClass(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setClose(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setExchange(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setHigh(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLow(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setOpen(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setSequenceId(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setVolume(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kaikosdk.StreamAggregatesOHLCVResponseV1.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAggregate();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getClass();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getClose();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getExchange();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getHigh();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLow();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getOpen();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getSequenceId();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUid();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getVolume();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
};


/**
 * optional string aggregate = 1;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.getAggregate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.setAggregate = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string class = 2;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.getClass = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.setClass = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string close = 3;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.getClose = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.setClose = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string exchange = 4;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.getExchange = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.setExchange = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string high = 5;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.getHigh = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.setHigh = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string low = 6;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.getLow = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.setLow = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string open = 7;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.getOpen = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.setOpen = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string sequence_id = 8;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.getSequenceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.setSequenceId = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string code = 9;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} returns this
*/
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional string uid = 11;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.setUid = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string volume = 12;
 * @return {string}
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.getVolume = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.kaikosdk.StreamAggregatesOHLCVResponseV1} returns this
 */
proto.kaikosdk.StreamAggregatesOHLCVResponseV1.prototype.setVolume = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


goog.object.extend(exports, proto.kaikosdk);
