# This is a basic workflow to help you get started with Actions

name: linter

# Controls when the action will run. 
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Runs a set of commands using the runners shell
      - name: npm install
        run: npm install
      
      - name: run lint
        run: npm run lint

      - name: run prettier
        run: npm run prettier
